// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWUzdiBTcWeTERFdoEbeHr-68Ukd-bCSU',
    appId: '1:341375878748:web:14e9d805b7b40637b98899',
    messagingSenderId: '341375878748',
    projectId: 'ecommerce-f44ae',
    authDomain: 'ecommerce-f44ae.firebaseapp.com',
    storageBucket: 'ecommerce-f44ae.firebasestorage.app',
    measurementId: 'G-W9KNL5XNM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyML4bEIS5yZRgxf5NrVUmgf2P3-Lx2Jo',
    appId: '1:341375878748:android:8ba2d94719721d7fb98899',
    messagingSenderId: '341375878748',
    projectId: 'ecommerce-f44ae',
    storageBucket: 'ecommerce-f44ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU8zVN2YF6bBrhxkkvb4qUNNZ2w7kS0dY',
    appId: '1:341375878748:ios:fa052ab19d860cb3b98899',
    messagingSenderId: '341375878748',
    projectId: 'ecommerce-f44ae',
    storageBucket: 'ecommerce-f44ae.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU8zVN2YF6bBrhxkkvb4qUNNZ2w7kS0dY',
    appId: '1:341375878748:ios:fa052ab19d860cb3b98899',
    messagingSenderId: '341375878748',
    projectId: 'ecommerce-f44ae',
    storageBucket: 'ecommerce-f44ae.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWUzdiBTcWeTERFdoEbeHr-68Ukd-bCSU',
    appId: '1:341375878748:web:5cc3e470924edcb5b98899',
    messagingSenderId: '341375878748',
    projectId: 'ecommerce-f44ae',
    authDomain: 'ecommerce-f44ae.firebaseapp.com',
    storageBucket: 'ecommerce-f44ae.firebasestorage.app',
    measurementId: 'G-TD6Q7TN3NR',
  );
}
